USE [master]
GO

/****** Object:  Database [Competition_task]    Script Date: 23-02-2022 15:58:13 ******/
CREATE DATABASE [Competition_task]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Competition_task', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IC\MSSQL\DATA\Competition_task.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Competition_task_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IC\MSSQL\DATA\Competition_task_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Competition_task].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Competition_task] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Competition_task] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Competition_task] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Competition_task] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Competition_task] SET ARITHABORT OFF 
GO

ALTER DATABASE [Competition_task] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Competition_task] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Competition_task] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Competition_task] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Competition_task] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Competition_task] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Competition_task] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Competition_task] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Competition_task] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Competition_task] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Competition_task] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Competition_task] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Competition_task] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Competition_task] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Competition_task] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Competition_task] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Competition_task] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Competition_task] SET RECOVERY FULL 
GO

ALTER DATABASE [Competition_task] SET  MULTI_USER 
GO

ALTER DATABASE [Competition_task] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Competition_task] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Competition_task] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Competition_task] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Competition_task] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Competition_task] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Competition_task] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Competition_task] SET  READ_WRITE 
GO


